2022-04-03 18:15:26.610 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-04 18:16:48.883 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-04 20:56:50.996 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-04 20:56:51.000 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
IndexOutOfRangeException: Index was outside the bounds of the array.
    Stack:    at System.Array.Clear(Array array, Int32 index, Int32 length)
   at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-04 20:56:51.000 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-04 20:56:51.000 [Error] IndexOutOfRangeException: Index was outside the bounds of the array.
    Stack:    at System.Array.Clear(Array array, Int32 index, Int32 length)
   at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-04 20:57:38.494 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-04 20:57:38.501 [Error] InvalidOperationException: Collection was modified; enumeration operation may not execute.
    Stack:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_13(CancellationToken cancellationToken)
   at Intersect.Client.Framework.Gwen.Control.Data.ValueTableCellDataProvider`1.<>c__DisplayClass1_1.<.ctor>b__3(Task _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Intersect.Async.AsyncValueGenerator`1.<DoLoop>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


--------------------------------------------------------------------------------
2022-04-04 20:58:00.634 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-04 20:58:00.636 [Error] InvalidOperationException: Collection was modified; enumeration operation may not execute.
    Stack:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_13(CancellationToken cancellationToken)
   at Intersect.Client.Framework.Gwen.Control.Data.ValueTableCellDataProvider`1.<>c__DisplayClass1_1.<.ctor>b__3(Task _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Intersect.Async.AsyncValueGenerator`1.<DoLoop>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


--------------------------------------------------------------------------------
2022-04-04 20:58:34.238 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-04 20:58:34.242 [Error] InvalidOperationException: Collection was modified; enumeration operation may not execute.
    Stack:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_13(CancellationToken cancellationToken)
   at Intersect.Client.Framework.Gwen.Control.Data.ValueTableCellDataProvider`1.<>c__DisplayClass1_1.<.ctor>b__3(Task _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Intersect.Async.AsyncValueGenerator`1.<DoLoop>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


--------------------------------------------------------------------------------
2022-04-04 21:20:36.197 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-04 21:20:36.199 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
IndexOutOfRangeException: Index was outside the bounds of the array.
    Stack:    at System.Array.Clear(Array array, Int32 index, Int32 length)
   at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-04 21:20:36.199 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-04 21:20:36.199 [Error] IndexOutOfRangeException: Index was outside the bounds of the array.
    Stack:    at System.Array.Clear(Array array, Int32 index, Int32 length)
   at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-04 21:28:26.182 [Error] ObjectDisposedException: The CancellationTokenSource has been disposed.
    Stack:    at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.Cancel()
   at Intersect.Async.CancellableGenerator`1.Dispose()
   at Intersect.Client.Interface.Debugging.DebugWindow.Dispose()
   at Intersect.Client.Framework.Gwen.Control.Base.<>c.<Dispose>b__192_0(Base child)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Intersect.Client.Framework.Gwen.Control.Base.Dispose()
   at Intersect.Client.Framework.Gwen.Control.Canvas.Dispose()
   at Intersect.Client.Interface.Game.GameInterface.Dispose()
   at Intersect.Client.Interface.Interface.InitGwen()
   at Intersect.Client.Core.Main.Logout(Boolean characterSelect)
   at Intersect.Client.Interface.Game.EscapeMenu.LogoutToCharacterSelect(Object sender, EventArgs e)
   at Intersect.Client.Interface.Game.EscapeMenu.GoToCharacterSelect_Clicked(Base sender, ClickedEventArgs arguments)
   at Intersect.Client.Framework.Gwen.Control.Base.OnMouseClickedLeft(Int32 x, Int32 y, Boolean down, Boolean automated)
   at Intersect.Client.Framework.Gwen.Control.Button.OnClicked(Int32 x, Int32 y)
   at Intersect.Client.Framework.Gwen.Control.Button.OnMouseClickedLeft(Int32 x, Int32 y, Boolean down, Boolean automated)
   at Intersect.Client.Framework.Gwen.Control.Base.InputMouseClickedLeft(Int32 x, Int32 y, Boolean down, Boolean automated)
   at Intersect.Client.Framework.Gwen.Input.InputHandler.OnMouseClicked(Base canvas, Int32 mouseButton, Boolean down)
   at Intersect.Client.Framework.Gwen.Control.Canvas.Input_MouseButton(Int32 button, Boolean down)
   at Intersect.Client.Framework.Gwen.Input.IntersectInput.ProcessMessage(Object message)
   at Intersect.Client.MonoGame.Input.MonoInput.CheckMouseButton(Keys modifier, ButtonState bs, MouseButtons mb)
   at Intersect.Client.MonoGame.Input.MonoInput.Update()
   at Intersect.Client.Core.Main.Update(TimeSpan deltaTime)
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-04-04 22:20:13.862 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-04 22:20:13.867 [Error] InvalidOperationException: Collection was modified; enumeration operation may not execute.
    Stack:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_13(CancellationToken cancellationToken)
   at Intersect.Client.Framework.Gwen.Control.Data.ValueTableCellDataProvider`1.<>c__DisplayClass1_1.<.ctor>b__3(Task _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Intersect.Async.AsyncValueGenerator`1.<DoLoop>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


--------------------------------------------------------------------------------
2022-04-04 23:01:05.914 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-04 23:01:05.917 [Error] InvalidOperationException: Collection was modified; enumeration operation may not execute.
    Stack:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_13(CancellationToken cancellationToken)
   at Intersect.Client.Framework.Gwen.Control.Data.ValueTableCellDataProvider`1.<>c__DisplayClass1_1.<.ctor>b__3(Task _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Intersect.Async.AsyncValueGenerator`1.<DoLoop>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


--------------------------------------------------------------------------------
2022-04-05 00:42:01.745 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-05 00:42:01.776 [Error] InvalidOperationException: Collection was modified; enumeration operation may not execute.
    Stack:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_13(CancellationToken cancellationToken)
   at Intersect.Client.Framework.Gwen.Control.Data.ValueTableCellDataProvider`1.<>c__DisplayClass1_1.<.ctor>b__3(Task _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Intersect.Async.AsyncValueGenerator`1.<DoLoop>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


--------------------------------------------------------------------------------
2022-04-06 00:16:08.246 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-06 00:16:08.295 [Error] InvalidOperationException: Collection was modified; enumeration operation may not execute.
    Stack:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_13(CancellationToken cancellationToken)
   at Intersect.Client.Framework.Gwen.Control.Data.ValueTableCellDataProvider`1.<>c__DisplayClass1_1.<.ctor>b__3(Task _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Intersect.Async.AsyncValueGenerator`1.<DoLoop>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


--------------------------------------------------------------------------------
2022-04-06 01:51:56.491 [Error] ObjectDisposedException: The CancellationTokenSource has been disposed.
    Stack:    at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.Cancel()
   at Intersect.Async.CancellableGenerator`1.Dispose()
   at Intersect.Client.Interface.Debugging.DebugWindow.Dispose()
   at Intersect.Client.Framework.Gwen.Control.Base.<>c.<Dispose>b__192_0(Base child)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Intersect.Client.Framework.Gwen.Control.Base.Dispose()
   at Intersect.Client.Framework.Gwen.Control.Canvas.Dispose()
   at Intersect.Client.Interface.Game.GameInterface.Dispose()
   at Intersect.Client.Interface.Interface.InitGwen()
   at Intersect.Client.Core.Main.Logout(Boolean characterSelect)
   at Intersect.Client.Interface.Game.EscapeMenu.LogoutToCharacterSelect(Object sender, EventArgs e)
   at Intersect.Client.Interface.Game.EscapeMenu.GoToCharacterSelect_Clicked(Base sender, ClickedEventArgs arguments)
   at Intersect.Client.Framework.Gwen.Control.Base.OnMouseClickedLeft(Int32 x, Int32 y, Boolean down, Boolean automated)
   at Intersect.Client.Framework.Gwen.Control.Button.OnClicked(Int32 x, Int32 y)
   at Intersect.Client.Framework.Gwen.Control.Button.OnMouseClickedLeft(Int32 x, Int32 y, Boolean down, Boolean automated)
   at Intersect.Client.Framework.Gwen.Control.Base.InputMouseClickedLeft(Int32 x, Int32 y, Boolean down, Boolean automated)
   at Intersect.Client.Framework.Gwen.Input.InputHandler.OnMouseClicked(Base canvas, Int32 mouseButton, Boolean down)
   at Intersect.Client.Framework.Gwen.Control.Canvas.Input_MouseButton(Int32 button, Boolean down)
   at Intersect.Client.Framework.Gwen.Input.IntersectInput.ProcessMessage(Object message)
   at Intersect.Client.MonoGame.Input.MonoInput.CheckMouseButton(Keys modifier, ButtonState bs, MouseButtons mb)
   at Intersect.Client.MonoGame.Input.MonoInput.Update()
   at Intersect.Client.Core.Main.Update(TimeSpan deltaTime)
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-04-06 01:57:49.349 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-06 01:57:49.352 [Error] InvalidOperationException: Collection was modified; enumeration operation may not execute.
    Stack:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_13(CancellationToken cancellationToken)
   at Intersect.Client.Framework.Gwen.Control.Data.ValueTableCellDataProvider`1.<>c__DisplayClass1_1.<.ctor>b__3(Task _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Intersect.Async.AsyncValueGenerator`1.<DoLoop>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


--------------------------------------------------------------------------------
2022-04-06 21:49:48.836 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-06 21:49:48.868 [Error] InvalidOperationException: Collection was modified; enumeration operation may not execute.
    Stack:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_13(CancellationToken cancellationToken)
   at Intersect.Client.Framework.Gwen.Control.Data.ValueTableCellDataProvider`1.<>c__DisplayClass1_1.<.ctor>b__3(Task _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Intersect.Async.AsyncValueGenerator`1.<DoLoop>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


--------------------------------------------------------------------------------
2022-04-06 22:28:14.978 [Error] Exception: Error loading json ui for InGame.CharacterWindow
    Stack:    at Intersect.Client.Framework.Gwen.Control.Base.<>c__DisplayClass205_0.<LoadJsonUi>b__0(String rawLayout, Boolean cacheHit)
   at Intersect.Client.Framework.File_Management.GameContentManager.<>c__DisplayClass60_0.<GetLayout>g__onLayoutReady|0()
   at Intersect.Client.Framework.File_Management.GameContentManager.<>c__DisplayClass60_0.<GetLayout>g__addChangeListener|1(String targetPath)
   at Intersect.Client.Framework.File_Management.GameContentManager.<>c__DisplayClass60_0.<GetLayout>g__addCreateOrChangeListener|2(String targetPath, Boolean createIfMissing)
   at Intersect.Client.Framework.File_Management.GameContentManager.GetLayout(UI stage, String name, String resolution, Boolean skipCache, Action`2 layoutHandler)
   at Intersect.Client.Framework.Gwen.Control.Base.LoadJsonUi(UI stage, String resolution, Boolean saveOutput)
   at Intersect.Client.Interface.Game.Character.CharacterWindow..ctor(Canvas gameCanvas)
   at Intersect.Client.Interface.Game.Menu..ctor(Canvas gameCanvas)
   at Intersect.Client.Interface.Game.GameInterface.InitGameGui()
   at Intersect.Client.Interface.Game.GameInterface..ctor(Canvas canvas)
   at Intersect.Client.Interface.Interface.InitGwen()
   at Intersect.Client.Interface.Interface.DrawGui()
   at Intersect.Client.Core.Graphics.Render(TimeSpan deltaTime)
   at Intersect.Client.MonoGame.IntersectGame.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)

Caused By
JsonReaderException: Unexpected character encountered while parsing value: b. Path 'InnerPanel.Children.EquipmentItem5.Texture', line 924, position 18.
    Stack:    at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Intersect.Client.Framework.Gwen.Control.Base.<>c__DisplayClass205_0.<LoadJsonUi>b__0(String rawLayout, Boolean cacheHit)


--------------------------------------------------------------------------------
2022-04-06 22:28:58.646 [Error] Exception: Error loading json ui for InGame.CharacterWindow
    Stack:    at Intersect.Client.Framework.Gwen.Control.Base.<>c__DisplayClass205_0.<LoadJsonUi>b__0(String rawLayout, Boolean cacheHit)
   at Intersect.Client.Framework.File_Management.GameContentManager.<>c__DisplayClass60_0.<GetLayout>g__onLayoutReady|0()
   at Intersect.Client.Framework.File_Management.GameContentManager.<>c__DisplayClass60_0.<GetLayout>g__addChangeListener|1(String targetPath)
   at Intersect.Client.Framework.File_Management.GameContentManager.<>c__DisplayClass60_0.<GetLayout>g__addCreateOrChangeListener|2(String targetPath, Boolean createIfMissing)
   at Intersect.Client.Framework.File_Management.GameContentManager.GetLayout(UI stage, String name, String resolution, Boolean skipCache, Action`2 layoutHandler)
   at Intersect.Client.Framework.Gwen.Control.Base.LoadJsonUi(UI stage, String resolution, Boolean saveOutput)
   at Intersect.Client.Interface.Game.Character.CharacterWindow..ctor(Canvas gameCanvas)
   at Intersect.Client.Interface.Game.Menu..ctor(Canvas gameCanvas)
   at Intersect.Client.Interface.Game.GameInterface.InitGameGui()
   at Intersect.Client.Interface.Game.GameInterface..ctor(Canvas canvas)
   at Intersect.Client.Interface.Interface.InitGwen()
   at Intersect.Client.Interface.Interface.DrawGui()
   at Intersect.Client.Core.Graphics.Render(TimeSpan deltaTime)
   at Intersect.Client.MonoGame.IntersectGame.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)

Caused By
JsonReaderException: Unexpected character encountered while parsing value: b. Path 'InnerPanel.Children.EquipmentItem5.Texture', line 924, position 18.
    Stack:    at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Intersect.Client.Framework.Gwen.Control.Base.<>c__DisplayClass205_0.<LoadJsonUi>b__0(String rawLayout, Boolean cacheHit)


--------------------------------------------------------------------------------
2022-04-06 22:29:23.638 [Error] Exception: Error loading json ui for InGame.CharacterWindow
    Stack:    at Intersect.Client.Framework.Gwen.Control.Base.<>c__DisplayClass205_0.<LoadJsonUi>b__0(String rawLayout, Boolean cacheHit)
   at Intersect.Client.Framework.File_Management.GameContentManager.<>c__DisplayClass60_0.<GetLayout>g__onLayoutReady|0()
   at Intersect.Client.Framework.File_Management.GameContentManager.<>c__DisplayClass60_0.<GetLayout>g__addChangeListener|1(String targetPath)
   at Intersect.Client.Framework.File_Management.GameContentManager.<>c__DisplayClass60_0.<GetLayout>g__addCreateOrChangeListener|2(String targetPath, Boolean createIfMissing)
   at Intersect.Client.Framework.File_Management.GameContentManager.GetLayout(UI stage, String name, String resolution, Boolean skipCache, Action`2 layoutHandler)
   at Intersect.Client.Framework.Gwen.Control.Base.LoadJsonUi(UI stage, String resolution, Boolean saveOutput)
   at Intersect.Client.Interface.Game.Character.CharacterWindow..ctor(Canvas gameCanvas)
   at Intersect.Client.Interface.Game.Menu..ctor(Canvas gameCanvas)
   at Intersect.Client.Interface.Game.GameInterface.InitGameGui()
   at Intersect.Client.Interface.Game.GameInterface..ctor(Canvas canvas)
   at Intersect.Client.Interface.Interface.InitGwen()
   at Intersect.Client.Interface.Interface.DrawGui()
   at Intersect.Client.Core.Graphics.Render(TimeSpan deltaTime)
   at Intersect.Client.MonoGame.IntersectGame.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)

Caused By
JsonReaderException: Unexpected character encountered while parsing value: b. Path 'InnerPanel.Children.EquipmentItem5.Texture', line 924, position 18.
    Stack:    at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Intersect.Client.Framework.Gwen.Control.Base.<>c__DisplayClass205_0.<LoadJsonUi>b__0(String rawLayout, Boolean cacheHit)


--------------------------------------------------------------------------------
2022-04-06 22:29:53.680 [Error] Exception: Error loading json ui for InGame.CharacterWindow
    Stack:    at Intersect.Client.Framework.Gwen.Control.Base.<>c__DisplayClass205_0.<LoadJsonUi>b__0(String rawLayout, Boolean cacheHit)
   at Intersect.Client.Framework.File_Management.GameContentManager.<>c__DisplayClass60_0.<GetLayout>g__onLayoutReady|0()
   at Intersect.Client.Framework.File_Management.GameContentManager.<>c__DisplayClass60_0.<GetLayout>g__addChangeListener|1(String targetPath)
   at Intersect.Client.Framework.File_Management.GameContentManager.<>c__DisplayClass60_0.<GetLayout>g__addCreateOrChangeListener|2(String targetPath, Boolean createIfMissing)
   at Intersect.Client.Framework.File_Management.GameContentManager.GetLayout(UI stage, String name, String resolution, Boolean skipCache, Action`2 layoutHandler)
   at Intersect.Client.Framework.Gwen.Control.Base.LoadJsonUi(UI stage, String resolution, Boolean saveOutput)
   at Intersect.Client.Interface.Game.Character.CharacterWindow..ctor(Canvas gameCanvas)
   at Intersect.Client.Interface.Game.Menu..ctor(Canvas gameCanvas)
   at Intersect.Client.Interface.Game.GameInterface.InitGameGui()
   at Intersect.Client.Interface.Game.GameInterface..ctor(Canvas canvas)
   at Intersect.Client.Interface.Interface.InitGwen()
   at Intersect.Client.Interface.Interface.DrawGui()
   at Intersect.Client.Core.Graphics.Render(TimeSpan deltaTime)
   at Intersect.Client.MonoGame.IntersectGame.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)

Caused By
JsonReaderException: Unexpected character encountered while parsing value: b. Path 'InnerPanel.Children.EquipmentItem5.Texture', line 924, position 18.
    Stack:    at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
   at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(JsonReader reader, JsonContract contract)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Intersect.Client.Framework.Gwen.Control.Base.<>c__DisplayClass205_0.<LoadJsonUi>b__0(String rawLayout, Boolean cacheHit)


--------------------------------------------------------------------------------
2022-04-06 22:56:27.175 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-06 22:56:27.178 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
IndexOutOfRangeException: Index was outside the bounds of the array.
    Stack:    at System.Array.Clear(Array array, Int32 index, Int32 length)
   at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-06 22:56:27.179 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-06 22:56:27.179 [Error] IndexOutOfRangeException: Index was outside the bounds of the array.
    Stack:    at System.Array.Clear(Array array, Int32 index, Int32 length)
   at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-08 22:12:53.643 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-08 22:12:53.657 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
IndexOutOfRangeException: Index was outside the bounds of the array.
    Stack:    at System.Array.Clear(Array array, Int32 index, Int32 length)
   at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-08 22:12:53.657 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-08 22:12:53.657 [Error] IndexOutOfRangeException: Index was outside the bounds of the array.
    Stack:    at System.Array.Clear(Array array, Int32 index, Int32 length)
   at System.Collections.Generic.List`1.RemoveAll(Predicate`1 match)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-10 18:13:09.948 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-10 18:13:09.974 [Error] InvalidOperationException: Collection was modified; enumeration operation may not execute.
    Stack:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_13(CancellationToken cancellationToken)
   at Intersect.Client.Framework.Gwen.Control.Data.ValueTableCellDataProvider`1.<>c__DisplayClass1_1.<.ctor>b__3(Task _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Intersect.Async.AsyncValueGenerator`1.<DoLoop>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


--------------------------------------------------------------------------------
2022-04-14 20:31:21.148 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-14 20:31:21.168 [Error] InvalidOperationException: Collection was modified; enumeration operation may not execute.
    Stack:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_13(CancellationToken cancellationToken)
   at Intersect.Client.Framework.Gwen.Control.Data.ValueTableCellDataProvider`1.<>c__DisplayClass1_1.<.ctor>b__3(Task _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Intersect.Async.AsyncValueGenerator`1.<DoLoop>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


--------------------------------------------------------------------------------
2022-04-14 20:31:47.459 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-14 20:31:47.462 [Error] InvalidOperationException: Collection was modified; enumeration operation may not execute.
    Stack:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Extensions.EnumerableExtensions.SelectManyRecursive[T](IEnumerable`1 source, Func`2 selector, CancellationToken cancellationToken)
   at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_13(CancellationToken cancellationToken)
   at Intersect.Client.Framework.Gwen.Control.Data.ValueTableCellDataProvider`1.<>c__DisplayClass1_1.<.ctor>b__3(Task _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Intersect.Async.AsyncValueGenerator`1.<DoLoop>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


--------------------------------------------------------------------------------
2022-04-25 14:36:35.167 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-25 14:36:35.177 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-25 14:36:35.178 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-25 14:36:35.178 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-28 12:58:34.883 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Client.Entities.Player.Update()
   at Intersect.Client.Core.Main.ProcessGame()
   at Intersect.Client.Core.Main.Update(TimeSpan deltaTime)
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-04-28 13:18:10.508 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Client.Entities.Player.Update()
   at Intersect.Client.Core.Main.ProcessGame()
   at Intersect.Client.Core.Main.Update(TimeSpan deltaTime)
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-04-28 14:24:58.379 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-28 14:24:58.384 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-28 14:24:58.384 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-28 14:24:58.384 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-28 14:48:55.519 [Error] InvalidOperationException: GetSkin: null
    Stack:    at Intersect.Client.Framework.Gwen.Control.Base.get_Skin()
   at Intersect.Client.Framework.Gwen.Control.Base.Dispose()
   at Intersect.Client.Interface.Debugging.DebugWindow.Dispose()
   at Intersect.Client.Interface.MutableInterface.DisposeDebugWindow()
   at Intersect.Client.Interface.Interface.DestroyGwen(Boolean exiting)
   at Intersect.Client.Core.Main.DestroyGame()
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-04-28 16:02:42.276 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Client.Entities.Player.Update()
   at Intersect.Client.Core.Main.ProcessGame()
   at Intersect.Client.Core.Main.Update(TimeSpan deltaTime)
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-04-28 23:34:47.431 [Error] InvalidOperationException: GetSkin: null
    Stack:    at Intersect.Client.Framework.Gwen.Control.Base.get_Skin()
   at Intersect.Client.Framework.Gwen.Control.Base.Dispose()
   at Intersect.Client.Interface.Debugging.DebugWindow.Dispose()
   at Intersect.Client.Interface.MutableInterface.DisposeDebugWindow()
   at Intersect.Client.Interface.Interface.DestroyGwen(Boolean exiting)
   at Intersect.Client.Core.Main.DestroyGame()
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-04-28 23:38:33.711 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-28 23:38:33.713 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-28 23:38:33.714 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-28 23:38:33.714 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-29 18:15:21.116 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Client.Networking.PacketHandler.HandlePacket(IPacketSender packetSender, GameObjectPacket packet)
   at Intersect.Network.PacketHandlerRegistry.<>c__DisplayClass38_1`2.<CreateWeaklyTypedDelegateForMethodInfo>b__1(IPacketSender packetSender, IPacket packet)
   at Intersect.Client.Networking.PacketHandler.HandlePacket(IPacket packet)
   at Intersect.Client.Networking.Network.MySocket_OnDataReceived(IPacket packet)
   at Intersect.Client.Framework.Network.GameSocket.OnDataReceived(IPacket packet)
   at Intersect.Client.MonoGame.Network.MonoSocket.Update()
   at Intersect.Client.Networking.Network.Update()
   at Intersect.Client.Core.Main.Update(TimeSpan deltaTime)
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-04-29 18:27:44.217 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-29 18:27:44.222 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-29 18:27:44.222 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-29 18:27:44.223 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-29 18:39:59.114 [Error] Received unhandled exception from Name:Intersect Client.exe
There are no context policies.
.

--------------------------------------------------------------------------------
2022-04-29 18:39:59.124 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_14(Base x)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Intersect.Client.Interface.Debugging.DebugWindow.<>c.<CreateTableDebugStats>b__29_13(CancellationToken cancellationToken)
   at Intersect.Client.Framework.Gwen.Control.Data.ValueTableCellDataProvider`1.<>c__DisplayClass1_1.<.ctor>b__3(Task _)
   at System.Threading.Tasks.ContinuationResultTaskFromTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Intersect.Async.AsyncValueGenerator`1.<DoLoop>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


--------------------------------------------------------------------------------
2022-04-29 18:41:00.405 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-29 18:41:00.407 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-29 18:41:00.407 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-29 18:41:00.407 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-29 18:56:13.640 [Error] InvalidOperationException: GetSkin: null
    Stack:    at Intersect.Client.Framework.Gwen.Control.Base.get_Skin()
   at Intersect.Client.Framework.Gwen.Control.Base.Dispose()
   at Intersect.Client.Interface.Debugging.DebugWindow.Dispose()
   at Intersect.Client.Interface.MutableInterface.DisposeDebugWindow()
   at Intersect.Client.Interface.Interface.DestroyGwen(Boolean exiting)
   at Intersect.Client.Core.Main.DestroyGame()
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-04-29 18:58:47.084 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-29 18:58:47.086 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-29 18:58:47.086 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-29 18:58:47.086 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-29 18:59:31.587 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-29 18:59:31.587 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-29 18:59:31.587 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-29 18:59:31.587 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-29 19:05:00.463 [Error] InvalidOperationException: GetSkin: null
    Stack:    at Intersect.Client.Framework.Gwen.Control.Base.get_Skin()
   at Intersect.Client.Framework.Gwen.Control.Base.Dispose()
   at Intersect.Client.Interface.Debugging.DebugWindow.Dispose()
   at Intersect.Client.Interface.MutableInterface.DisposeDebugWindow()
   at Intersect.Client.Interface.Interface.DestroyGwen(Boolean exiting)
   at Intersect.Client.Core.Main.DestroyGame()
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-04-29 23:27:44.501 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-29 23:27:44.503 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-29 23:27:44.503 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-29 23:27:44.503 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-29 23:54:02.540 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-29 23:54:02.542 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-29 23:54:02.542 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-29 23:54:02.542 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-29 23:55:52.641 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-29 23:55:52.641 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-29 23:55:52.641 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-29 23:55:52.641 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-30 00:29:33.431 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-30 00:29:33.433 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-30 00:29:33.433 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-30 00:29:33.433 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-30 21:54:34.375 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-04-30 21:54:34.404 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-30 21:54:34.404 [Error] Caused by:

--------------------------------------------------------------------------------
2022-04-30 21:54:34.404 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-04-30 23:25:57.027 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Client.Networking.PacketHandler.HandlePacket(IPacketSender packetSender, GameObjectPacket packet)
   at Intersect.Network.PacketHandlerRegistry.<>c__DisplayClass38_1`2.<CreateWeaklyTypedDelegateForMethodInfo>b__1(IPacketSender packetSender, IPacket packet)
   at Intersect.Client.Networking.PacketHandler.HandlePacket(IPacket packet)
   at Intersect.Client.Networking.Network.MySocket_OnDataReceived(IPacket packet)
   at Intersect.Client.Framework.Network.GameSocket.OnDataReceived(IPacket packet)
   at Intersect.Client.MonoGame.Network.MonoSocket.Update()
   at Intersect.Client.Networking.Network.Update()
   at Intersect.Client.Core.Main.Update(TimeSpan deltaTime)
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-05-01 00:40:11.512 [Error] InvalidOperationException: GetSkin: null
    Stack:    at Intersect.Client.Framework.Gwen.Control.Base.get_Skin()
   at Intersect.Client.Framework.Gwen.Control.Base.Dispose()
   at Intersect.Client.Interface.Debugging.DebugWindow.Dispose()
   at Intersect.Client.Interface.MutableInterface.DisposeDebugWindow()
   at Intersect.Client.Interface.Interface.DestroyGwen(Boolean exiting)
   at Intersect.Client.Core.Main.DestroyGame()
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-05-01 14:40:53.236 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Client.Entities.Player.Update()
   at Intersect.Client.Core.Main.ProcessGame()
   at Intersect.Client.Core.Main.Update(TimeSpan deltaTime)
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-05-01 15:26:28.887 [Error] InvalidOperationException: GetSkin: null
    Stack:    at Intersect.Client.Framework.Gwen.Control.Base.get_Skin()
   at Intersect.Client.Framework.Gwen.Control.Base.Dispose()
   at Intersect.Client.Interface.Debugging.DebugWindow.Dispose()
   at Intersect.Client.Interface.MutableInterface.DisposeDebugWindow()
   at Intersect.Client.Interface.Interface.DestroyGwen(Boolean exiting)
   at Intersect.Client.Core.Main.DestroyGame()
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-05-01 15:36:32.245 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-05-01 15:36:32.249 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-05-01 15:36:32.249 [Error] Caused by:

--------------------------------------------------------------------------------
2022-05-01 15:36:32.249 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-05-01 15:37:54.872 [Error] InvalidOperationException: GetSkin: null
    Stack:    at Intersect.Client.Framework.Gwen.Control.Base.get_Skin()
   at Intersect.Client.Framework.Gwen.Control.Base.Dispose()
   at Intersect.Client.Interface.Debugging.DebugWindow.Dispose()
   at Intersect.Client.Interface.MutableInterface.DisposeDebugWindow()
   at Intersect.Client.Interface.Interface.DestroyGwen(Boolean exiting)
   at Intersect.Client.Core.Main.DestroyGame()
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-05-01 15:38:09.822 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-05-01 15:38:09.824 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-05-01 15:38:09.824 [Error] Caused by:

--------------------------------------------------------------------------------
2022-05-01 15:38:09.824 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-05-01 15:49:06.332 [Error] InvalidOperationException: GetSkin: null
    Stack:    at Intersect.Client.Framework.Gwen.Control.Base.get_Skin()
   at Intersect.Client.Framework.Gwen.Control.Base.Dispose()
   at Intersect.Client.Interface.Debugging.DebugWindow.Dispose()
   at Intersect.Client.Interface.MutableInterface.DisposeDebugWindow()
   at Intersect.Client.Interface.Interface.DestroyGwen(Boolean exiting)
   at Intersect.Client.Core.Main.DestroyGame()
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
2022-05-01 15:51:27.676 [Error] Received unhandled exception from System.Threading.Tasks.ContinuationTaskFromTask.

--------------------------------------------------------------------------------
2022-05-01 15:51:27.678 [Error] AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread.

Caused By
ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-05-01 15:51:27.678 [Error] Caused by:

--------------------------------------------------------------------------------
2022-05-01 15:51:27.678 [Error] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
    Stack:    at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Intersect.Client.Framework.Content.ContentWatcher.<>c__DisplayClass12_0.<Modify>b__0(Task completedTask)
   at System.Threading.Tasks.Task.Execute()


--------------------------------------------------------------------------------
2022-05-01 16:44:57.970 [Error] NullReferenceException: Object reference not set to an instance of an object.
    Stack:    at Intersect.Client.Entities.Player.Update()
   at Intersect.Client.Core.Main.ProcessGame()
   at Intersect.Client.Core.Main.Update(TimeSpan deltaTime)
   at Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   at Intersect.Client.Core.ClientContext.InternalStart()
   at Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)


--------------------------------------------------------------------------------
